
--ADD CONSTRAINTS to User TABLE
ALTER TABLE Users
ADD CONSTRAINT UsersPk
PRIMARY KEY (UserId) ;

ALTER TABLE Users
ADD CONSTRAINT UniqueUserName UNIQUE (UserName);

ALTER TABLE Users
ADD CONSTRAINT UniqueEmailAddress UNIQUE (EmailAddress);

ALTER TABLE Users
ADD CONSTRAINT UniqueMobileNo UNIQUE (MobileNo);

--ADD CONSTRAINTS to Chat TABLE
ALTER TABLE Chat
ADD CONSTRAINT ChatPK
PRIMARY KEY (ChatId) ;

ALTER TABLE Chat
ADD CONSTRAINT ChatFK1
FOREIGN KEY (Sender)  REFERENCES Users(UserId) ON DELETE CASCADE;

ALTER TABLE Chat
ADD CONSTRAINT ChatFK2
FOREIGN KEY (Receiver)  REFERENCES Users(UserId) ON DELETE CASCADE;

ALTER TABLE Chat
MODIFY COLUMN CreatedAt DATETIME DEFAULT DATETIME;

ALTER TABLE Chat
ADD CONSTRAINT CheckReceiverNotNull CHECK (Receiver IS NOT NULL);

ALTER TABLE Chat
ADD CONSTRAINT CheckSenderNotEquaRecipient
CHECK (Sender <> Receiver);

ALTER TABLE Messages
ADD CONSTRAINT CheckSenderNotNull CHECK (Sender IS NOT NULL);

--ADD CONSTRAINT to Message TABLE
ALTER TABLE Message
ADD CONSTRAINT ConversationsPK
PRIMARY KEY (ConversationsId);

ALTER TABLE Message
ADD CONSTRAINT MessageFK
FOREIGN KEY (ChatId)  REFERENCES Chat(ChatId);

ALTER TABLE Message
ADD CONSTRAINT CheckContentLength CHECK (LENGTH(Content) <= 4096);

