
ALTER TABLE Users 
ADD CONSTRAINT UsersDF
DEFAULT GETDATE() FOR CreatedAt;

ALTER TABLE Chat 
ADD CONSTRAINT ChatDF
DEFAULT GETDATE() FOR CreatedAt;

ALTER TABLE Message 
ADD CONSTRAINT MessageDF
DEFAULT GETDATE() FOR CreatedAt;
