# Liquibase migration 
name: Main
on:
  - push
jobs:

  liquibase_job:
    runs-on: ubuntu-latest
    steps:
  databaseChangeLog:
  - changeSet:
   id:  sqlFile-example
   author:  liquibase-docs
   changes:
      - sqlFile:
       dbms:  '!h2,  oracle,  mysql'
       endDelimiter:  \nGO
       splitStatements:  true
       path:  my/path/file.sql
       stripComments:  true